fos_ck_editor:
#    default_config: my_config
#    configs:
#        my_config:
#            toolbar: "full"
#            uiColor:                "#000000"
#            filebrowserUploadRoute: "my_route"
#            extraPlugins:           "wordcount"
#    toolbars:
#        items:
#            full.colors: [ "TextColor", "BGColor" ]
#            full.document: [ "Source", "-", "Preview", "Print" ]