jms_translation:
    source_language: 'cs'

    configs:
        app:
            dirs: ["%kernel.root_dir%", "%kernel.root_dir%/../templates"]
            output_dir: "%kernel.root_dir%/../translations"
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [var, bin, logs, assets]
            output_format: xliff