
// generated by script at path /api/client
const apiPrefix = '/api';
export default {
  ProjectTranslation: {
    get: (locale, id) => apiPrefix + '/projects/translations/' + id + '?_locale=' + locale
  },
  Project: {
    getAll: (locale) => apiPrefix + '/projects?_locale=' + locale,
    postNew: (locale) => apiPrefix + '/projects?_locale=' + locale,
    get: (locale, id) => apiPrefix + '/projects/' + id + '?_locale=' + locale,
    put: (locale, id) => apiPrefix + '/projects/' + id + '?_locale=' + locale
  },
  Plan: {
    getAll: (locale) => apiPrefix + '/plans?_locale=' + locale,
    postNew: (locale) => apiPrefix + '/plans?_locale=' + locale,
    get: (locale, id) => apiPrefix + '/plans/' + id + '?_locale=' + locale,
    put: (locale, id) => apiPrefix + '/plans/' + id + '?_locale=' + locale
  },
  PlanTranslation: {
    get: (locale, id) => apiPrefix + '/plans/translations/' + id + '?_locale=' + locale
  },
  PlayersProject: {
    getAll: (locale) => apiPrefix + '/players_projects?_locale=' + locale,
    postNew: (locale) => apiPrefix + '/players_projects?_locale=' + locale,
    get: (locale, id) => apiPrefix + '/players_projects/' + id + '?_locale=' + locale,
    put: (locale, id) => apiPrefix + '/players_projects/' + id + '?_locale=' + locale
  },
  School: {
    getAll: (locale) => apiPrefix + '/schools?_locale=' + locale,
    postNew: (locale) => apiPrefix + '/schools?_locale=' + locale,
    get: (locale, id) => apiPrefix + '/schools/' + id + '?_locale=' + locale,
    put: (locale, id) => apiPrefix + '/schools/' + id + '?_locale=' + locale
  },
  Team: {
    getAll: (locale) => apiPrefix + '/teams?_locale=' + locale,
    postNew: (locale) => apiPrefix + '/teams?_locale=' + locale,
    get: (locale, id) => apiPrefix + '/teams/' + id + '?_locale=' + locale,
    put: (locale, id) => apiPrefix + '/teams/' + id + '?_locale=' + locale
  },
  TeamTranslation: {
    get: (locale, id) => apiPrefix + '/weathers/translations/' + id + '?_locale=' + locale
  },
  Turn: {
    getAll: (locale) => apiPrefix + '/turns?_locale=' + locale,
    postNew: (locale) => apiPrefix + '/turns?_locale=' + locale,
    get: (locale, id) => apiPrefix + '/turns/' + id + '?_locale=' + locale,
    put: (locale, id) => apiPrefix + '/turns/' + id + '?_locale=' + locale
  },
  TurnTranslation: {
    get: (locale, id) => apiPrefix + '/works/translations/' + id + '?_locale=' + locale
  },
  User: {
    getAll: (locale) => apiPrefix + '/users?_locale=' + locale,
    postNew: (locale) => apiPrefix + '/users?_locale=' + locale,
    get: (locale, id) => apiPrefix + '/users/' + id + '?_locale=' + locale,
    put: (locale, id) => apiPrefix + '/users/' + id + '?_locale=' + locale
  },
  Weather: {
    getAll: (locale) => apiPrefix + '/weathers?_locale=' + locale,
    postNew: (locale) => apiPrefix + '/weathers?_locale=' + locale,
    get: (locale, id) => apiPrefix + '/weathers/' + id + '?_locale=' + locale,
    put: (locale, id) => apiPrefix + '/weathers/' + id + '?_locale=' + locale
  },
  WeatherTranslation: {
    get: (locale, id) => apiPrefix + '/weathers/translations/' + id + '?_locale=' + locale
  },
  Work: {
    getAll: (locale) => apiPrefix + '/works?_locale=' + locale,
    postNew: (locale) => apiPrefix + '/works?_locale=' + locale,
    get: (locale, id) => apiPrefix + '/works/' + id + '?_locale=' + locale,
    put: (locale, id) => apiPrefix + '/works/' + id + '?_locale=' + locale
  },
  WorkTranslation: {
    get: (locale, id) => apiPrefix + '/works/translations/' + id + '?_locale=' + locale
  },
  Planning: {
    get: (locale, plan) => apiPrefix + '/plans/' + plan + '/planning?_locale=' + locale
  },
  PlanSlot: {
    inPlan: (locale, plan) => apiPrefix + '/plans/' + plan + '/slots/?_locale=' + locale,
    get: (locale, plan, work, turn) => apiPrefix + '/plans/' + plan + '/slots/' + work + '/' + turn + '?_locale=' + locale,
    put: (locale, plan, work, turn) => apiPrefix + '/plans/' + plan + '/slots/' + work + '/' + turn + '?_locale=' + locale,
    moveTeam: (locale, plan, work, turn) => apiPrefix + '/plans/' + plan + '/slots/' + work + '/' + turn + '/move-team/work?_locale=' + locale
  },
  PlanSlotMoveTeams: {
    post: (locale, plan, work, turn, team) => apiPrefix + '/plans/' + plan + '/slots/' + work + '/' + turn + '/teams/' + team + '/move?_locale=' + locale
  }
};
